pass the reason for failure up from MemoryBuffer and report it in diagnostics when we fail to open a file.  This allows us to report things like:
$ clang test.c -I.
test.c:2:10: fatal error: error opening file './foo.h': Permission denied
#include "foo.h"
         ^

llvm-svn: 90276