[flang][Driver] Fix lto-flags.f90 on Solaris
The `Flang :: Driver/lto-flags.f90` test `FAIL`s on Solaris:

  /vol/llvm/src/llvm-project/dist/flang/test/Driver/lto-flags.f90:30:13: error: THIN-LTO: expected string not found in input
  ! THIN-LTO: "-plugin-opt=thinlto"
              ^

This is no wonder since the native Solaris `ld` doesn't support the linker
plugin interface at all, so this patch marks the test as `UNSUPPORTED`.

Tested on `amd64-pc-solaris2.11` and `x86_64-pc-linux-gnu`.

Differential Revision: https://reviews.llvm.org/D146807