[flang] Remove unused variable lastPrivBlock (NFC)
This fixes the warning:

  llvm-project/flang/lib/Lower/OpenMP.cpp:94:10: error: unused
  variable 'lastPrivBlock' [-Werror,-Wunused-variable]